---
version: "3"

services:
  lufi:
    container_name: lufi
    image: "hamzelot/lufi"
    ports:
      - 8080:8081
    volumes:
      - "data:/files"
    restart: "unless-stopped"
    environment:
      URL_LENGTH: 8
      MAX_FILE_SIZE: 104857600
      MAX_DELAY: 180
      USE_PROXY: 0
      ALLOW_PWD: 1
      CONTACT_HTML: "<a href= 'your-website.eu'>here</a>" 
      REPORT_EMAIL: "name@email.eu"
      SITE_NAME: lufi

volumes:
  data:
